# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hw2Q5_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(402, 477)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_Q5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Q5.setGeometry(QtCore.QRect(50, 30, 301, 381))
        self.groupBox_Q5.setObjectName("groupBox_Q5")
        self.ButtonQ5_1 = QtWidgets.QPushButton(self.groupBox_Q5)
        self.ButtonQ5_1.setGeometry(QtCore.QRect(30, 40, 241, 41))
        self.ButtonQ5_1.setObjectName("ButtonQ5_1")
        self.ButtonQ5_2 = QtWidgets.QPushButton(self.groupBox_Q5)
        self.ButtonQ5_2.setGeometry(QtCore.QRect(30, 100, 241, 41))
        self.ButtonQ5_2.setObjectName("ButtonQ5_2")
        self.ButtonQ5_4 = QtWidgets.QPushButton(self.groupBox_Q5)
        self.ButtonQ5_4.setGeometry(QtCore.QRect(30, 310, 241, 41))
        self.ButtonQ5_4.setObjectName("ButtonQ5_4")
        self.groupBox_Q5_3 = QtWidgets.QGroupBox(self.groupBox_Q5)
        self.groupBox_Q5_3.setGeometry(QtCore.QRect(20, 160, 261, 141))
        self.groupBox_Q5_3.setObjectName("groupBox_Q5_3")
        self.ButtonQ5_3 = QtWidgets.QPushButton(self.groupBox_Q5_3)
        self.ButtonQ5_3.setGeometry(QtCore.QRect(10, 80, 241, 41))
        self.ButtonQ5_3.setObjectName("ButtonQ5_3")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_Q5_3)
        self.spinBox.setGeometry(QtCore.QRect(10, 40, 241, 31))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(999)
        self.spinBox.setObjectName("spinBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 402, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_Q5.setTitle(_translate("MainWindow", "5. Dogs and Cats classification Using ResNet50"))
        self.ButtonQ5_1.setText(_translate("MainWindow", "5.1 Show Model Structure"))
        self.ButtonQ5_2.setText(_translate("MainWindow", "5.2  Show Tensorboard"))
        self.ButtonQ5_4.setText(_translate("MainWindow", "5.4 Randomly select a picture"))
        self.groupBox_Q5_3.setTitle(_translate("MainWindow", "5.3 Test"))
        self.ButtonQ5_3.setText(_translate("MainWindow", "5.3 Test"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
